[34m[1mwandb[0m: [32m[41mERROR[0m artifact '0:latest' not found in 'shoon06/GAN'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/public/api.py", line 1210, in _artifact
    artifact = wandb.Artifact._from_name(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 279, in _from_name
    raise ValueError(f"artifact '{name}' not found in '{entity}/{project}'")
ValueError: artifact '0:latest' not found in 'shoon06/GAN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/default/Generative-Model/GAN/inference.py", line 100, in <module>
    main()
  File "/root/default/Generative-Model/GAN/inference.py", line 76, in main
    artifact = wandb.use_artifact(f"{project}/{config['ver']}:latest", type="model")
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 403, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3071, in use_artifact
    artifact = public_api._artifact(type=type, name=name)
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 71, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/wandb/apis/public/api.py", line 1210, in _artifact
    artifact = wandb.Artifact._from_name(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 279, in _from_name
    raise ValueError(f"artifact '{name}' not found in '{entity}/{project}'")
wandb.errors.errors.CommError: artifact '0:latest' not found in 'shoon06/GAN'
