Current device is cuda
Traceback (most recent call last):
  File "/root/default/Generative-Model/GAN/main.py", line 166, in <module>
    main()
  File "/root/default/Generative-Model/GAN/main.py", line 76, in main
    set_random_seed(config["seed"])
KeyError: 'seed'
